/*
  作用：定义action的type类型
 */

export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const RESET_USER_INFO = 'RESET_USER_INFO';
export const UPDATE_USER_LIST = 'UPDATE_USER_LIST';
export const RESET_USER_LIST = 'RESET_USER_LIST';
export const GET_CHAT_MESSAGES = 'GET_CHAT_MESSAGES';
export const RESET_CHAT_MESSAGES = 'RESET_CHAT_MESSAGES';
export const UPDATE_CHAT_MESSAGES = 'UPDATE_CHAT_MESSAGES';